name: Sync Fork with Upstream Releases

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  repository_dispatch:
    types: [test-sync]

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Set Upstream Repo URL
        run: echo "UPSTREAM_REPO_URL=${{ github.event.client_payload.upstream_url || vars.UPSTREAM_REPO_URL }}" >> $GITHUB_ENV

      - name: Add upstream remote
        run: |
          git remote add upstream ${{ env.UPSTREAM_REPO_URL }}
          git fetch upstream --tags

      - name: Get latest and previous tags
        id: get_tags
        run: |
          # Get all tags from upstream sorted by creation date (newest first)
          TAGS=($(git ls-remote --tags --refs upstream | awk -F/ '{print $3}' | sort -V -r))
          
          # Get latest and previous tags
          LATEST_TAG="${TAGS[0]}"
          PREVIOUS_TAG="${TAGS[1]}"
          
          # Output tags for debugging
          echo "Latest tag: ${LATEST_TAG}"
          echo "Previous tag: ${PREVIOUS_TAG}"
          
          # Set environment variables
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV
          echo "PREVIOUS_TAG=${PREVIOUS_TAG}" >> $GITHUB_ENV

      - name: Create or update customizations.patch
        run: |
          git checkout main
          
          mkdir -p .github/patches
          
          # Create temporary branch
          git branch temp-branch $PREVIOUS_TAG || exit 1
          
          # Create the patch file
          git diff temp-branch..main > .github/patches/customizations.patch
          
          git add .github/patches/customizations.patch
          git commit -m "chore: update customizations patch file" || echo "No changes to commit"
          git push origin main
          
          # Clean up temp branch
          git branch -D temp-branch || true

      - name: Check if release exists locally
        id: check_release
        run: |
          if git show-ref --tags --quiet --verify -- "refs/tags/${{ steps.latest_release.outputs.LATEST_TAG }}"; then
            echo "EXISTS=true" >> $GITHUB_OUTPUT
          else
            echo "EXISTS=false" >> $GITHUB_OUTPUT
          fi
          echo "Output: $GITHUB_OUTPUT"

      - name: Attempt merge
        id: merge_attempt
        if: steps.check_release.outputs.EXISTS == 'false'
        env:
          UPSTREAM_REPO_URL: ${{ env.UPSTREAM_REPO_URL }}
          LATEST_TAG: ${{ env.LATEST_TAG }}
          PREVIOUS_TAG: ${{ env.PREVIOUS_TAG }}
        run: |
          BRANCH_NAME="sync-${LATEST_TAG}"
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV

          git checkout -b $BRANCH_NAME
          if git merge ${LATEST_TAG} --no-edit; then
            echo "MERGE_STATUS=clean" >> $GITHUB_OUTPUT
          else
            git merge --abort
            echo "MERGE_STATUS=conflicts" >> $GITHUB_OUTPUT
          fi
          echo "Output: $GITHUB_OUTPUT"

      - name: Apply custom patches
        id: patch_apply
        run: |
          PATCH_FILE=".github/patches/customizations.patch"
          if [ "${{ github.event_name }}" = "repository_dispatch" ] && [ "${{ github.event.action }}" = "test-sync" ]; then
            PATCH_FILE=".github/patches/test-customizations.patch"
          fi

          if [ -f $PATCH_FILE ]; then
            if git apply --check $PATCH_FILE; then
              git apply $PATCH_FILE
              echo "PATCH_STATUS=success" >> $GITHUB_OUTPUT
            else
              echo "PATCH_STATUS=failed" >> $GITHUB_OUTPUT
            fi
          fi
          echo "Output: $GITHUB_OUTPUT"

      - name: Push changes
        if: steps.check_release.outputs.EXISTS == 'false' && steps.merge_attempt.outputs.MERGE_STATUS == 'clean'
        run: |
          git push origin ${{ env.BRANCH_NAME }}

      - name: Create Pull Request
        if: steps.check_release.outputs.EXISTS == 'false' && steps.merge_attempt.outputs.MERGE_STATUS == 'clean'
        uses: peter-evans/create-pull-request@v5
        id: create_pr
        with:
          title: 'Sync: Upstream release ${{ env.LATEST_TAG }}'
          body: |
            This PR synchronizes our fork with upstream release ${{ env.LATEST_TAG }}.
            - Merge Status: ${{ steps.merge_attempt.outputs.MERGE_STATUS }}
            - Patch Status: ${{ steps.patch_apply.outputs.PATCH_STATUS }}
            This PR will be automatically merged if there are no conflicts.
          branch: ${{ env.BRANCH_NAME }}
          base: main
          labels: sync,automated
          delete-branch: true
          push-to-fork: ''

      - name: Debug Auto-merge Conditions
        if: always()
        run: |
          echo "PR Operation: ${{ steps.create_pr.outputs.pull-request-operation }}"
          echo "Merge Status: ${{ steps.merge_attempt.outputs.MERGE_STATUS }}"
          echo "Patch Status: ${{ steps.patch_apply.outputs.PATCH_STATUS }}"
          echo "PR Number: ${{ steps.create_pr.outputs.pull-request-number }}"
          
          # Print condition evaluation
          echo "Condition 1 (PR created): ${{ steps.create_pr.outputs.pull-request-operation == 'created' }}"
          echo "Condition 2 (Clean merge): ${{ steps.merge_attempt.outputs.MERGE_STATUS == 'clean' }}"
          echo "Condition 3 (Patch success): ${{ steps.patch_apply.outputs.PATCH_STATUS == 'success' }}"
        
      - name: Create Issue for Manual Resolution
        if: |
          steps.merge_attempt.outputs.MERGE_STATUS != 'clean' || 
          steps.patch_apply.outputs.PATCH_STATUS != 'success'
        uses: actions/github-script@v6
        with:
          script: |
            const issueBody = `
            ### Sync Fork Conflict Detection
            
            Manual intervention needed to sync fork with upstream release ${{ env.LATEST_TAG }}.
            
            **Debug Information:**
            - Merge Status: ${{ steps.merge_attempt.outputs.MERGE_STATUS }}
            - Patch Status: ${{ steps.patch_apply.outputs.PATCH_STATUS }}
            - Branch Name: ${{ env.BRANCH_NAME }}
            
            Please resolve the conflicts manually and sync the fork.
            
            > This issue was automatically created by the sync-fork workflow.
            `;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Manual Resolution Needed: Fork Sync Conflicts for ${process.env.LATEST_TAG}`,
              body: issueBody,
              labels: ['sync', 'conflict', 'needs-attention']
            });

      - name: Auto-merge Pull Request
        if: |
          steps.create_pr.outputs.pull-request-operation == 'created' && 
          steps.merge_attempt.outputs.MERGE_STATUS == 'clean' && 
          steps.patch_apply.outputs.PATCH_STATUS == 'success'
        run: |
          echo "Attempting to merge PR #${{ steps.create_pr.outputs.pull-request-number }}"
          gh pr merge ${{ steps.create_pr.outputs.pull-request-number }} --auto --merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}