name: Test Sync Workflow

on:
  workflow_dispatch:

env:
  WORKFLOW_NAME: "Sync Fork with Upstream Releases" # The name of the main workflow to be triggered

jobs:
  test-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Create annotated mock tag
        id: create_tags
        run: |
            TAG_NAME="mock-tag-$(date +%s)"
            echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
            git tag $TAG_NAME
            git push origin $TAG_NAME

      - name: Dispatch main workflow
        id: trigger_main_workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          UPSTREAM_URL="https://github.com/${GITHUB_REPOSITORY}"
          TAG_NAME="${{ env.TAG_NAME }}"
          echo "{ \"event_type\": \"test-sync\", \"client_payload\": { \"tag\": \"${TAG_NAME}\", \"upstream_url\": \"${UPSTREAM_URL}\" }}" > payload.json
          gh api \
            --method POST \
            /repos/${GITHUB_REPOSITORY}/dispatches \
            --input payload.json
          rm -f payload.json

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Poll main workflow status
        id: poll_status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install PyGithub
          python .github/scripts/poll_workflow.py "${{ env.WORKFLOW_NAME }}" "${{ github.repository }}"
          STATUS=$?
          if [ $STATUS -eq 0 ]; then
            echo "RUN_CONCLUSION=success" >> $GITHUB_ENV
          else
            echo "RUN_CONCLUSION=failure" >> $GITHUB_ENV
          fi

      - name: Verify main workflow success
        if: env.RUN_CONCLUSION != 'success'
        run: |
          echo "Main workflow failed. Exiting..."
          exit 1

      - name: Cleanup tags and branches
        if: always()
        run: |
          # Reset test patch file
          echo "No patch applied" > .github/test/test-patch.md || true
          git add .github/test/repos/upstream/test-patch.md || true
          git config --global user.name 'GitHub Actions' || true
          git config --global user.email 'actions@github.com' || true
          git commit -m "test: reset test patch file" || true
          git push origin main || true
      
          # Cleanup tags and branches
          TAG_NAME="${{ env.TAG_NAME }}"
          git push origin :refs/tags/$TAG_NAME || true
          git branch -D sync-$TAG_NAME || true
          git push origin --delete sync-$TAG_NAME || true