name: Test Sync Workflow

on:
  workflow_dispatch:

jobs:
  test-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Create annotated mock tag
        id: create_tags
        run: |
            TAG_NAME="mock-tag-$(date +%s)"
            echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
            git tag $TAG_NAME
            git push origin $TAG_NAME

      - name: Dispatch main workflow
        id: trigger_main_workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          UPSTREAM_URL="https://github.com/${GITHUB_REPOSITORY}"
          TAG_NAME="${{ env.TAG_NAME }}"
          echo "{ \"event_type\": \"test-sync\", \"client_payload\": { \"tag\": \"${TAG_NAME}\", \"upstream_url\": \"${UPSTREAM_URL}\" }}" > payload.json
          gh api \
            --method POST \
            /repos/${GITHUB_REPOSITORY}/dispatches \
            --input payload.json

      - name: Poll main workflow status
        id: poll_status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          WORKFLOW_NAME="Sync Fork with Upstream Releases"
          TAG_NAME=${{ env.TAG_NAME }}
          MAX_ATTEMPTS=30  # 5 minutes timeout (10 seconds * 30)
          ATTEMPT=0

          poll_for_workflow_run() {
            while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
              RUNS=$(gh api -H "Accept: application/vnd.github+json" \
                /repos/${GITHUB_REPOSITORY}/actions/runs \
                -q ".workflow_runs[] | select(.name == \"$WORKFLOW_NAME\" and .event == \"repository_dispatch\" and .head_branch == \"sync/$TAG_NAME\") | [.id, .status, .conclusion] | @csv" | head -n 1)
              
              if [[ -z "$RUNS" ]]; then
                echo "No workflow run found. Attempt $ATTEMPT of $MAX_ATTEMPTS"
                ATTEMPT=$((ATTEMPT + 1))
                sleep 10
                continue
              fi

              IFS=',' read -r -a RUN_DATA <<< "$RUNS"
              RUN_ID=${RUN_DATA[0]//\"/}
              STATUS=${RUN_DATA[1]//\"/}
              CONCLUSION=${RUN_DATA[2]//\"/}

              echo "Current status: $STATUS, conclusion: $CONCLUSION"

              if [[ "$STATUS" == "completed" ]]; then
                echo "RUN_STATUS=$STATUS" >> $GITHUB_ENV
                echo "RUN_CONCLUSION=$CONCLUSION" >> $GITHUB_ENV
                
                if [[ "$CONCLUSION" != "success" ]]; then
                  echo "Workflow failed with conclusion: $CONCLUSION"
                  exit 1
                fi
                return 0
              fi

              ATTEMPT=$((ATTEMPT + 1))
              sleep 10
            done

            echo "Timeout reached while waiting for workflow completion"
            exit 1
          }

          poll_for_workflow_run

      - name: Verify main workflow success
        if: env.RUN_CONCLUSION != 'success'
        run: exit 1

      - name: Cleanup tags and branches
        run: |
          TAG_NAME="${{ env.TAG_NAME }}"
          git push origin :refs/tags/$TAG_NAME
          git branch -D sync/$TAG_NAME || true
          git push origin --delete sync/$TAG_NAME || true