name: Test Sync Fork Workflow

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Configure Git for tests
        run: |
          git config --global user.name 'Test User'
          git config --global user.email 'test@example.com'

      - name: Create test repositories
        run: |
          set -e  # Exit on first error
          
          # Create test upstream repo
          mkdir -p ${GITHUB_WORKSPACE}/test_repos/upstream
          cd ${GITHUB_WORKSPACE}/test_repos/upstream
          git init
          echo "initial" > file.txt
          git add .
          git commit -m "Initial commit"
          git tag -f v1.0.0
          echo "Upstream repository created at $(pwd)"
          ls -la ${GITHUB_WORKSPACE}/test_repos/upstream

          # Create test fork repo
          cd ${GITHUB_WORKSPACE}/test_repos
          git clone ${GITHUB_WORKSPACE}/test_repos/upstream fork
          cd fork
          git remote add upstream ${GITHUB_WORKSPACE}/test_repos/upstream
          echo "Fork repository created at $(pwd)"
          ls -la ${GITHUB_WORKSPACE}/test_repos/fork

          # Validate repository setup
          echo "Remotes for fork:"
          git remote -v

          # Create test patch
          mkdir -p ${GITHUB_WORKSPACE}/test_repos/fork/.github/patches
          echo "test patch" > ${GITHUB_WORKSPACE}/test_repos/fork/.github/patches/customizations.patch
          echo "Patch file created at ${GITHUB_WORKSPACE}/test_repos/fork/.github/patches/customizations.patch"
          ls -la ${GITHUB_WORKSPACE}/test_repos/fork/.github/patches/

      - name: Debug Print Paths
        run: |
          echo "Listing all directories and files in the workspace"
          ls -R ${GITHUB_WORKSPACE}/test_repos

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-mock gitpython PyGithub

      - name: Run tests
        run: |
          pytest tests/ -v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEST_REPOS_PATH: ${{ github.workspace }}/test_repos